#!/bin/sh
### BEGIN INIT INFO
# Provides:          ikecsvc
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop `ikec` server daemo
# Description:       Control `ikec` instance
### END INIT INFO

DAEMON="/etc/init.d/ikew"
DESC="Ike VPN connect"
STARTUP_OPTS="ikec -r 88.208.104.30 -a"

test -x "$DAEMON" || exit 0

. /lib/lsb/init-functions

do_start(){
    start-stop-daemon --start --oknodo --background --exec "$DAEMON" --chuid 1000 -- $STARTUP_OPTS
}

do_stop(){
    kill -15 $(ps -A |grep ikec |awk '{ print $1 }')
}

status_of_proc_ikec () {
    pid=$(ps -A |grep ikec |awk '{ print $1 }')
    case "$pid" in
  	  *[!\ ]*)
        log_success_msg "$DESC is running"
        return 0;;
  	  *)
        log_failure_msg "$DESC is not running"
        return 1;;
	esac
}

test_run_ikec () {
    pid=$(ps -A |grep ikec |awk '{ print $1 }')
    case "$pid" in
  	  *[!\ ]*)
        log_success_msg "$DESC is already running"
        exit 0;;
  	  *)
        return 1;;
	esac
}

case "$1" in
  start)
    test_run_ikec
    log_begin_msg "Starting $DESC"
    do_start
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping $DESC"
    do_stop
    log_end_msg $?
    ;;
  restart)
    log_begin_msg "Restarting $DESC"
    if do_stop; then
        do_start
    fi
    log_end_msg $?
    ;;
  status)
    status_of_proc_ikec
    ;;
  *)
    N=/etc/init.d/${0##*/}
    echo "Usage: $N {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
