#!/bin/sh
### BEGIN INIT INFO
# Provides:          ikedsvc
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop `iked` server daemo
# Description:       Control `iked` instance
### END INIT INFO

DAEMON="/usr/sbin/iked"
PIDFILE="/var/run/iked.pid"
DESC="Iked daemon"
STARTUP_OPTS="-d 0 -p $PIDFILE"

test -x "$DAEMON" || exit 0

. /lib/lsb/init-functions


do_start(){
    start-stop-daemon --start --oknodo --background --exec "$DAEMON" -- $STARTUP_OPTS
}

do_stop(){
    start-stop-daemon --stop --retry 5 --oknodo --pidfile $PIDFILE
}

case "$1" in
  start)
    log_begin_msg "Starting $DESC"
    do_start
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping $DESC"
    do_stop
    log_end_msg $?
    rm -f $PIDFILE
    ;;
  restart)
    log_begin_msg "Restarting $DESC"
    if do_stop; then
        do_start
    fi
    log_end_msg $?
    ;;
  status)
        status_of_proc -p $PIDFILE "$DAEMON" && exit 0 || exit $?
    ;;
  *)
    N=/etc/init.d/${0##*/}
    echo "Usage: $N {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
